C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw ADM100_EN_Col24.pdf ADM100_EN_Col24.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw ADM103_EN_Col23.pdf ADM103_EN_Col23.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw ADM110_EN_Col25.pdf ADM110_EN_Col25.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw ADM325_EN_Col23.pdf ADM325_EN_Col23.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw ADM800_EN_Col23.pdf ADM800_EN_Col23.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw HA200_EN_Col19_v2.pdf HA200_EN_Col19_v2.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw SAPTEC.23.EN-US.pdf SAPTEC.23.EN-US.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw TADM10_1_EN_Col23_v2.pdf TADM10_1_EN_Col23_v2.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw TADM10_2_EN_Col23_v2.pdf TADM10_2_EN_Col23_v2.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw TADM12_1_EN_Col23_v1.pdf TADM12_1_EN_Col23_v1.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw TADM12_2_EN_Col23_v1.pdf TADM12_2_EN_Col23_v1.txt
C:\Users\bartik\Documents\poppler\Library\bin\pdftotext.exe -raw UX200_EN_Col24.pdf UX200_EN_Col24.txt
